### ISSUE TITLE
curl command

### ISSUE THREAD

**Issue by urupvog** [culturekings/facebook-messenger-bot-webhook#2]
For me, this doesn't seem to be running. I could successfully add the webhook on FB. However, when I write a message in chat, I do not get a message back. 

I think the error is that the server isnt subscribing to events. Where do we run the curl command ? should we run it on heroku server or local ?

**Comment by evulse** [comment]
Yeah you likely just need to run the curl command. You can run it anywhere that you can execute curl. So run it locally or on the server whichever you find easier. I might add this as an automated script during server boot

**Comment by urupvog** [comment]
I tried running on both. Unfortunately, it still doesnt work. I cross checked verify token and page token, and both seems to be fine.

**Comment by urupvog** [comment]
Update:
I just received this on FB:
We've noticed that your Webhooks subscription for callback URL https://xxx.herokuapp.com/webhook/ has not been accepting updates for at least 16 minutes. Please verify that your callback server is functioning so you may continue to receive updates.

**Comment by evulse** [comment]
Can you click on View Log in your Heroku App. Can you see requests coming through?

**Comment by evulse** [comment]
Its the under the 3 dots in the admin panel.

**Comment by urupvog** [comment]
These are the last 100 lines of log
`heroku logs --app pcbot1 
/Users/purugovind/.heroku/client/lib/heroku/jsplugin.rb:109: warning: Insecure world writable dir /usr/local in PATH, mode 040777
2016-04-15T08:01:53.786538+00:00 app[web.1]:     at expressInit (/app/node_modules/express/lib/middleware/init.js:33:5)
2016-04-15T08:01:53.786538+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:01:53.880324+00:00 heroku[router]: at=info method=POST path="/webhook/" host=pcbot1.herokuapp.com request_id=6737cc31-c9a3-4194-b5a5-ca509c2f3f38 fwd="66.220.158.111" dyno=web.1 connect=0ms service=1ms status=500 bytes=232
2016-04-15T08:01:54.093545+00:00 heroku[router]: at=info method=POST path="/webhook/" host=pcbot1.herokuapp.com request_id=266a017a-12de-4498-a811-5684398ba6cf fwd="173.252.120.97" dyno=web.1 connect=1ms service=3ms status=500 bytes=232
2016-04-15T08:01:53.999631+00:00 app[web.1]: TypeError: Cannot read property 'entry' of undefined
2016-04-15T08:01:53.999676+00:00 app[web.1]:     at /app/index.js:21:32
2016-04-15T08:01:53.999679+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:01:53.999680+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:131:13)
2016-04-15T08:01:53.999680+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2016-04-15T08:01:53.999681+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:01:53.999682+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:277:22
2016-04-15T08:01:53.999682+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
2016-04-15T08:01:53.999684+00:00 app[web.1]:     at expressInit (/app/node_modules/express/lib/middleware/init.js:33:5)
2016-04-15T08:01:53.999683+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:271:10)
2016-04-15T08:01:53.999685+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:01:54.403527+00:00 heroku[router]: at=info method=POST path="/webhook/" host=pcbot1.herokuapp.com request_id=b3c36a3a-3953-454e-80c6-fea366e3f47f fwd="66.220.158.110" dyno=web.1 connect=2ms service=8ms status=500 bytes=232
2016-04-15T08:01:54.309656+00:00 app[web.1]: TypeError: Cannot read property 'entry' of undefined
2016-04-15T08:01:54.309667+00:00 app[web.1]:     at /app/index.js:21:32
2016-04-15T08:01:54.309669+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:01:54.309670+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:131:13)
2016-04-15T08:01:54.309672+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2016-04-15T08:01:54.309673+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:01:54.309674+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:277:22
2016-04-15T08:01:54.309775+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
2016-04-15T08:01:54.309776+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:271:10)
2016-04-15T08:01:54.309777+00:00 app[web.1]:     at expressInit (/app/node_modules/express/lib/middleware/init.js:33:5)
2016-04-15T08:01:54.309778+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:01:55.205603+00:00 heroku[router]: at=info method=POST path="/webhook/" host=pcbot1.herokuapp.com request_id=04c67420-2857-449c-91ca-f3927e6b4db5 fwd="173.252.120.119" dyno=web.1 connect=3ms service=10ms status=500 bytes=232
2016-04-15T08:01:55.098811+00:00 app[web.1]: TypeError: Cannot read property 'entry' of undefined
2016-04-15T08:01:55.098820+00:00 app[web.1]:     at /app/index.js:21:32
2016-04-15T08:01:55.098821+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:01:55.098821+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:131:13)
2016-04-15T08:01:55.098822+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2016-04-15T08:01:55.098823+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:01:55.098823+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:277:22
2016-04-15T08:01:55.098824+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
2016-04-15T08:01:55.098825+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:271:10)
2016-04-15T08:01:55.098825+00:00 app[web.1]:     at expressInit (/app/node_modules/express/lib/middleware/init.js:33:5)
2016-04-15T08:01:55.098826+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:01:58.233415+00:00 heroku[router]: at=info method=POST path="/webhook/" host=pcbot1.herokuapp.com request_id=e77f3dcf-65b7-4e29-a823-d5be7bbf298b fwd="173.252.120.105" dyno=web.1 connect=1ms service=3ms status=500 bytes=232
2016-04-15T08:01:58.136046+00:00 app[web.1]: TypeError: Cannot read property 'entry' of undefined
2016-04-15T08:01:58.136057+00:00 app[web.1]:     at /app/index.js:21:32
2016-04-15T08:01:58.136059+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:01:58.136060+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:131:13)
2016-04-15T08:01:58.136060+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2016-04-15T08:01:58.136061+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:01:58.136061+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:277:22
2016-04-15T08:01:58.136062+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
2016-04-15T08:01:58.136063+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:271:10)
2016-04-15T08:01:58.136063+00:00 app[web.1]:     at expressInit (/app/node_modules/express/lib/middleware/init.js:33:5)
2016-04-15T08:01:58.136064+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:02:05.428483+00:00 app[web.1]: TypeError: Cannot read property 'entry' of undefined
2016-04-15T08:02:05.428495+00:00 app[web.1]:     at /app/index.js:21:32
2016-04-15T08:02:05.428496+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:02:05.428497+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:131:13)
2016-04-15T08:02:05.428498+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2016-04-15T08:02:05.428499+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:02:05.428499+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:277:22
2016-04-15T08:02:05.428500+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
2016-04-15T08:02:05.428501+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:271:10)
2016-04-15T08:02:05.428501+00:00 app[web.1]:     at expressInit (/app/node_modules/express/lib/middleware/init.js:33:5)
2016-04-15T08:02:05.428502+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:02:05.522986+00:00 heroku[router]: at=info method=POST path="/webhook/" host=pcbot1.herokuapp.com request_id=7619767a-e249-4feb-b264-ac2980d12484 fwd="173.252.120.117" dyno=web.1 connect=0ms service=2ms status=500 bytes=232
2016-04-15T08:02:14.498278+00:00 heroku[router]: at=info method=POST path="/webhook/" host=pcbot1.herokuapp.com request_id=3d95b07d-9a82-4a35-aabe-2897e5328c5d fwd="66.220.158.103" dyno=web.1 connect=2ms service=4ms status=500 bytes=232
2016-04-15T08:02:14.400194+00:00 app[web.1]: TypeError: Cannot read property 'entry' of undefined
2016-04-15T08:02:14.400213+00:00 app[web.1]:     at /app/index.js:21:32
2016-04-15T08:02:14.400215+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:131:13)
2016-04-15T08:02:14.400214+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:02:14.400216+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2016-04-15T08:02:14.400217+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:02:14.400218+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:277:22
2016-04-15T08:02:14.400219+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
2016-04-15T08:02:14.400219+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:271:10)
2016-04-15T08:02:14.400220+00:00 app[web.1]:     at expressInit (/app/node_modules/express/lib/middleware/init.js:33:5)
2016-04-15T08:02:14.400221+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:03:18.359461+00:00 heroku[router]: at=info method=POST path="/webhook/" host=pcbot1.herokuapp.com request_id=fc1ce184-458f-46c6-94ba-4fa3198128a3 fwd="173.252.120.96" dyno=web.1 connect=3ms service=7ms status=500 bytes=232
2016-04-15T08:03:18.259959+00:00 app[web.1]: TypeError: Cannot read property 'entry' of undefined
2016-04-15T08:03:18.259993+00:00 app[web.1]:     at /app/index.js:21:32
2016-04-15T08:03:18.259995+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:03:18.259996+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:131:13)
2016-04-15T08:03:18.259997+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2016-04-15T08:03:18.259997+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:03:18.259998+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:277:22
2016-04-15T08:03:18.259998+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
2016-04-15T08:03:18.260024+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:271:10)
2016-04-15T08:03:18.260025+00:00 app[web.1]:     at expressInit (/app/node_modules/express/lib/middleware/init.js:33:5)
2016-04-15T08:03:18.260025+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-04-15T08:03:36.292866+00:00 heroku[run.6261]: Process exited with status 0
`

**Comment by evulse** [comment]
Sorry this is fully working now, I've updated the code. You might need to redeploy to run the latest version.

**Comment by urupvog** [comment]
It worked when I just deployed on heroku from github. 

However, I just created a clone of it and re-deployed on Heroku -  and I am getting same error. What were your changes ?.

**Comment by evulse** [comment]
In your index.js file there should be the following new line which was missing. Can you confirm if this is present on your deployed version

```
var bodyParser = require('body-parser');
```

**Comment by urupvog** [comment]
This works. Though I downloaded the newer version, I was still deploying the older one. Sigh! Thanks and great work.  :)
